version: '2'
services:
  dspace:
    build: ./dspace
    image: dspace:latest
    command: ["env", "/wait-for-it.sh", "postgres:5432", "--strict", "--", "/entry.sh"]
    container_name: dspace
    environment:
      PGPASSWORD: dspace
    depends_on:
      - postgres
    ports:
      - 80:80
      - 8080:8080
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: dspace
      POSTGRES_USER: dspace
      POSTGRES_DB: dspace
    ports:
      - 5432:5432
