version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/dspace.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/dspace.tar | true
      - run:
          name: Build dspace Docker image
          command: |
            docker build --cache-from=dspace -t dspace:latest -t dspace:5.x knowledgearc-DSpace
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/dspace.tar dspace
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/dspace.tar
      - deploy:
          name: Push dspace Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u AWS -p ${ECR_PASSWORD} https://${ECR_ENDPOINT}
              docker tag dspace "${ECR_ENDPOINT}/dspace:latest"
              docker push "${ECR_ENDPOINT}/dspace:latest"
            fi